<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3in_wordlink"
 *
 * Auto generated by Extension Builder 2017-11-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'T3IN - Add Url to Words',
    'description' => 'Apply Url to words',
    'category' => 'be',
    'author' => 'Vikram Mandal',
    'author_email' => 'vikram@fivee.in',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
